[[wakes]]
name = "minecraft"
command = "sh"
arguments = ["-c", "firefox"]
# arguments = ["jar", "--nogui"]
working_directory = "/home/jonathan/"


[[wakes]]
name = "ssh"
command = "ssh-once"
working_directory = "~"

[[wakes]]
name="ls"
command = "sh ls"
arguments = ["-la"]
working_directory = "/home/jonathan/"

[[wakes]]
name="sleep"
command = "sleep"
arguments=["10"]
